import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const lacquerFont = localFont({
  src: './fonts/Lacquer-Regular.ttf',
  variable: '--font-lacquer', // Better to name it after the actual font
  display: 'swap', // Add for better font loading behavior
});
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lacquerFont.variable}`}>
        {children}
      </body>
    </html>
  );
}
